name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # --- Build the Vite app in /frontend ---
      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Build
        working-directory: frontend
        run: npm run build

      # --- Deploy: point to /frontend and its build output, skip Oryx build ---
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # In GitHub mode you do NOT need to pass a token.
          app_location: frontend           # where index.html / vite project lives
          output_location: dist            # path is relative to app_location
          api_location: api                # keep if your Azure Functions are in /api
          skip_app_build: true             # we built above with Vite
          skip_api_build: true             # set false if you actually need Oryx to build API

