name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    # run on pushes, and on PR events except "closed"
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # Build the Vite app in /frontend
      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Build
        working-directory: frontend
        run: npm run build

      # Deploy (GitHub mode – no token needed)
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload                 # <- REQUIRED
          app_location: frontend         # folder with your Vite app
          output_location: dist          # folder produced by "npm run build"
          api_location: api              # your Functions folder (keep if present)
          skip_app_build: true           # we already built above
          skip_api_build: true           # set to false if you want Oryx to build API

  close_pull_request_job:
    # when a PR to main is closed, tell SWA to remove the preview env
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close SWA PR environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: close                  # <- REQUIRED for PR-close
          app_location: frontend
          output_location: dist
          api_location: api


