name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # --- Build your Vite app in /frontend ---
      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Build
        working-directory: frontend
        run: npm run build
      # ---------------------------------------

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # CHANGE THIS SECRET NAME if your Azure portal gave you a different one
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

          # 👇 This line fixes "deployment_action was not provided"
          action: "upload"

          # We already built with Vite above, so skip the action's build and upload the artifact we produced
          skip_app_build: true
          app_artifact_location: frontend/dist

          # Paths in your repo (used for routing and API upload)
          app_location: frontend
          api_location: api

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request Environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"

